apiVersion: apps/v1
kind: Deployment
metadata:
  name: pps-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pps
  template:
    metadata:
      labels:
        app: pps
    spec:
      containers:
        - name: pps-container
          image: pps:1.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pps-service
spec:
  selector:
    app: pps
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
